In [1]:
TE = joinpath(homedir(), "Downloads", "TensorFunction.test", "")

if isdir(TE)

    rm(TE; recursive = true)

end

mkdir(TE)

println("Made ", TE, ".")

Made /Users/kwat/Downloads/TensorFunction.test/.


In [2]:
using Revise

---

In [3]:
using TensorFunction

┌ Info: Precompiling TensorFunction [7b8185a8-3a2a-4818-8ce3-c04382ef042b]
└ @ Base loading.jl:1342


## apply

In [4]:
n_ro = 5

n_co = 4

n_ze = convert(Int64, n_co / 2)

n_on = n_co - n_ze

2

In [5]:
bi_ = convert(BitVector, [zeros(n_ze); ones(n_on)])

4-element BitVector:
 0
 0
 1
 1

In [6]:
ve = convert(Vector{Float64}, [10^(id - 1) for id = 1:n_co])

4-element Vector{Float64}:
    1.0
   10.0
  100.0
 1000.0

In [7]:
ma = convert(Matrix{Float64}, reshape(1:n_ro*n_co, (n_ro, n_co)))

5×4 Matrix{Float64}:
 1.0   6.0  11.0  16.0
 2.0   7.0  12.0  17.0
 3.0   8.0  13.0  18.0
 4.0   9.0  14.0  19.0
 5.0  10.0  15.0  20.0

In [8]:
apply(bi_, ve, .*)

2-element Vector{Float64}:
   100.0
 10000.0

In [9]:
apply(ve, ma, .*)

5-element Vector{Any}:
 [1.0, 60.0, 1100.0, 16000.0]
 [2.0, 70.0, 1200.0, 17000.0]
 [3.0, 80.0, 1300.0, 18000.0]
 [4.0, 90.0, 1400.0, 19000.0]
 [5.0, 100.0, 1500.0, 20000.0]

In [10]:
apply(bi_, ma, .*)

5-element Vector{Any}:
 [11.0, 96.0]
 [24.0, 119.0]
 [39.0, 144.0]
 [56.0, 171.0]
 [75.0, 200.0]

In [11]:
apply(ma, ma, (ro1, ro2) -> minimum([ro1; ro2]))

5×5 Matrix{Any}:
 1.0  1.0  1.0  1.0  1.0
 1.0  2.0  2.0  2.0  2.0
 1.0  2.0  3.0  3.0  3.0
 1.0  2.0  3.0  4.0  4.0
 1.0  2.0  3.0  4.0  5.0

---

In [12]:
rm(TE; recursive = true)

println("Removed ", TE, ".")

Removed /Users/kwat/Downloads/TensorFunction.test/.
